In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
import os
from sklearn.cluster import MiniBatchKMeans
from sklearn.cluster import KMeans
from sklearn import metrics
import scipy.sparse


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/
%ls *.csv

/content/drive/MyDrive
wiki_movie_plots_deduped.csv


In [ ]:
dir_file = os.getcwd() # returns path to current directory
files_dir = os.listdir(dir_file)  # list of files in current directory

csv_files = [f for f in files_dir if f.endswith('csv')]
print(csv_files)
movie_file = csv_files[0]

movie_df = pd.read_csv(movie_file)
print(movie_df.columns)  # the columns
print(movie_df.shape)
movie_df.head()

['wiki_movie_plots_deduped.csv']
Index(['Release Year', 'Title', 'Origin/Ethnicity', 'Director', 'Cast',
       'Genre', 'Wiki Page', 'Plot'],
      dtype='object')
(34886, 8)


Release Year                             Title Origin/Ethnicity  \
0          1901            Kansas Saloon Smashers         American   
1          1901     Love by the Light of the Moon         American   
2          1901           The Martyred Presidents         American   
3          1901  Terrible Teddy, the Grizzly King         American   
4          1902            Jack and the Beanstalk         American   

                             Director Cast    Genre  \
0                             Unknown  NaN  unknown   
1                             Unknown  NaN  unknown   
2                             Unknown  NaN  unknown   
3                             Unknown  NaN  unknown   
4  George S. Fleming, Edwin S. Porter  NaN  unknown   

                                           Wiki Page  \
0  https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1  https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2  https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3  https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4  https://en.wikipedia.org/wiki/Jack_and_the_Bea...   

                                                Plot  
0  A bartender is working at a saloon, serving dr...  
1  The moon, painted with a smiling face hangs ov...  
2  The film, just over a minute long, is composed...  
3  Lasting just 61 seconds and consisting of two ...  
4  The earliest known adaptation of the classic f...

In [ ]:
# Get the top 35 genres
top_genres = movie_df['Genre'].value_counts().head(11).index.tolist()[1:]
# Display the array
print(top_genres)

['drama', 'comedy', 'horror', 'action', 'thriller', 'romance', 'western', 'crime', 'adventure', 'musical']


In [ ]:
# Remove rows where 'Genre' is labeled as 'unknown'
data_filtered = movie_df[['Plot', 'Genre']][movie_df['Genre'].isin(top_genres)]
data_filtered.head()

# Confirm the removal by checking the counts of 'unknown' in the Genre column
filtered_unknown_count = data_filtered['Genre'].value_counts().get('unknown', 0)
print("Count of 'unknown' in filtered data:", filtered_unknown_count)


Count of 'unknown' in filtered data: 0


#Write a Naiive Bayes Classifier
#Use Naive Bayes to classify a novel document as some genre

In [ ]:
import numpy as np
import spacy   # another tokenizer, lemmatizer (has --> be)
nlp = spacy.load('en_core_web_sm')
nlp.disable_pipes('parser', 'ner')

['parser', 'ner']

In [ ]:
def nlp_processing(doc): # from indexing.ipyns
    tokens = nlp(doc)

    #print(type(tokens))
    # eliminates stop words  and non alpha num and converts all to lower case
    terms = [token.lemma_.lower() for token in tokens if token.is_alpha and (not token.is_stop)]

    return terms

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Assuming 'plot' is your text column and 'genre' or another column is your target
X = data_filtered['Plot']  # Replace 'plot' with your actual text column
y = data_filtered['Genre']  # Replace 'genre' with your target class column

# Convert text to feature vectors
vectorizer = CountVectorizer(tokenizer = nlp_processing, min_df = 30) # ? why 50
X_vectorized = vectorizer.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.2, random_state=42)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Define parameter grid for alpha
param_grid = {'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]}

# Instantiate GridSearchCV with MultinomialNB and alpha parameter grid
grid_search = GridSearchCV(MultinomialNB(), param_grid, cv=5, scoring='accuracy')

# Train the model with grid search
grid_search.fit(X_train, y_train)

# Retrieve the best model and its parameters
best_nb_classifier = grid_search.best_estimator_
best_alpha = grid_search.best_params_['alpha']
print(f"Best alpha: {best_alpha}")

# Predict on the test set using the best model
y_pred = best_nb_classifier.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy with optimized alpha: {accuracy:.2f}')


Best alpha: 0.1
Accuracy with optimized alpha: 0.56


In [ ]:
# Predict on the test set
y_pred = best_nb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')
recall = metrics.recall_score(y_test, y_pred, average='weighted')
print(f'Recall: {recall:.2f}')
precision = metrics.precision_score(y_test, y_pred, average='weighted')
print(f'Precision: {precision:.2f}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted')
print(f'F1 Score (weighted): {f1:.2f}')

# Macro and Micro averaged scores
macro_f1 = f1_score(y_test, y_pred, average='macro')
micro_f1 = f1_score(y_test, y_pred, average='micro')
print(f'Macro-averaged F1: {macro_f1:.2f}')
print(f'Micro-averaged F1: {micro_f1:.2f}')

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.56
Recall: 0.56
Precision: 0.58
F1 Score (weighted): 0.56
Macro-averaged F1: 0.51
Micro-averaged F1: 0.56

Confusion Matrix:
[[121   9   5   8  11   4   0  34  10   2]
 [  4  61   6   2  16   1   1   1   1   2]
 [ 28  33 491  17 172  16  38  56  25   6]
 [ 11   1  25  50  21   4   1   0  14   1]
 [ 52  55 183  38 642  20  19 134  41  21]
 [  4   1   9   1  14 191   2   9  16   0]
 [  0   2  30   1  12   0  37   3   0   3]
 [  5   1  15   0  41   1   6 107   1   1]
 [ 17   7  18   6  43  34   0  19  42   0]
 [  1   4   4   3  11   1   2   1   0 145]]


#Use Bert to Classify some novel document as some genre



In [ ]:
import torch
!nvidia-smi

Sun Dec  8 22:49:39 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.empty_cache()

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [ ]:
# 1. Install and upgrade necessary packages (Jupyter Notebook)
#!pip install --upgrade sentence-transformers transformers datasets scikit-learn

# After running the above cell, manually restart the runtime/kernel.

# 2. Import Libraries
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from sentence_transformers import SentenceTransformer
import torch
from torch import nn
from sklearn.metrics import accuracy_score, recall_score, precision_score


X = data_filtered['Plot']   # Replace 'Plot' with your actual text column
y = data_filtered['Genre']  # Replace 'Genre' with your target class column

# Encode labels as integers
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# 4. Create InputExamples
class ClassificationDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts.tolist()
        self.labels = labels.tolist()

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return self.texts[idx], self.labels[idx]

train_dataset = ClassificationDataset(X_train, y_train)
test_dataset = ClassificationDataset(X_test, y_test)

# 5. Create DataLoaders
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=32)
test_dataloader = DataLoader(test_dataset, shuffle=False, batch_size=32)

# 6. Initialize the Model with Classification Head
class ClassificationModel(nn.Module):
    def __init__(self, transformer_model, num_labels):
        super(ClassificationModel, self).__init__()
        self.transformer = transformer_model
        self.classifier = nn.Linear(transformer_model.get_sentence_embedding_dimension(), num_labels)

    def forward(self, input_texts):
        embeddings = self.transformer.encode(input_texts, convert_to_tensor=True, device=device)
        logits = self.classifier(embeddings)
        return logits

# Initialize SentenceTransformer
transformer_model = SentenceTransformer('all-MiniLM-L6-v2')

# Initialize Classification Model
num_classes = len(le.classes_)
model = ClassificationModel(transformer_model, num_classes)

# Move model to GPU if available
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model.to(device)

# 7. Define Loss Function and Optimizer
criterion = nn.NLLLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=2e-5)

# 8. Training Loop
epochs = 20

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch in train_dataloader:
        texts, labels = batch
        labels = torch.tensor(labels).to(device)

        optimizer.zero_grad()
        outputs = model(texts)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_dataloader)
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {avg_loss:.4f}")

    # Evaluation
    model.eval()
    preds = []
    true_labels = []
    with torch.no_grad():
        for batch in test_dataloader:
            texts, labels = batch
            labels = labels.to(device)
            outputs = model(texts)
            _, predicted = torch.max(outputs, 1)
            preds.extend(predicted.cpu().numpy())
            true_labels.extend(labels.cpu().numpy())



    # 2. Calculate Metrics
    accuracy = accuracy_score(true_labels, preds)
    recall = recall_score(true_labels, preds, average='weighted')     # Use 'macro' or 'micro' based on your needs
    precision = precision_score(true_labels, preds, average='weighted')  # Use 'macro' or 'micro' based on your needs
    f1 = f1_score(true_labels, preds, average='weighted')

    macro_f1 = f1_score(true_labels, preds, average='macro')
    micro_f1 = f1_score(true_labels, preds, average='micro')

    # 3. Print Metrics
    print(f"Validation Accuracy:  {accuracy:.4f}")
    print(f"Validation Recall:     {recall:.4f}")
    print(f"Validation Precision:  {precision:.4f}")
    print(f"Validation F1 Score:   {f1:.4f}")
    print(f"Macro-Averaged F1:     {macro_f1:.4f}")
    print(f"Micro-Averaged F1:     {micro_f1:.4f}")

    # 4. Confusion Matrix
    conf_matrix = confusion_matrix(true_labels, preds)
    print("\nConfusion Matrix:")
    print(conf_matrix)

# 9. Save the Trained Model
torch.save(model.state_dict(), 'classification_model.pth')


/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Epoch 1/20, Loss: -0.0445
Validation Accuracy:  0.2777
Validation Recall:     0.2777
Validation Precision:  0.2659
Validation F1 Score:   0.2199
Macro-Averaged F1:     0.0963
Micro-Averaged F1:     0.2777

Confusion Matrix:
[[  0   0  10   7 135   0   0   4  22  26]
 [  0   0   2   6  41   0   1   5   5  35]
 [  0   4  79  15 535   7   6   5  37 194]
 [  0   0   5   2  78   0   0   1   2  40]
 [  1   0  54  24 749   8   6  29  59 275]
 [  0   0   9   6 190   7   0   6   3  26]
 [  0   0   5   2  50   0   1   1   1  28]
 [  0   1  17   7  99   0   4   1  25  24]
 [  0   0  10   4 120   5   0   3  13  31]
 [  0   0   3   2  75   2   0   0   2  88]]


<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Epoch 2/20, Loss: -0.0983


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3356
Validation Recall:     0.3356
Validation Precision:  0.2780
Validation F1 Score:   0.2454
Macro-Averaged F1:     0.1052
Micro-Averaged F1:     0.3356

Confusion Matrix:
[[  0   0   7   2 165   1   0   2  11  16]
 [  0   0   6   3  60   0   0   1   4  21]
 [  0   1 110   3 667   5   1   5  15  75]
 [  0   0   8   1  96   0   0   0   0  23]
 [  0   0  69   8 937   3   2  18  31 137]
 [  0   0   9   3 216   4   0   1   2  12]
 [  0   0  10   1  64   0   0   0   0  13]
 [  0   0  17   1 143   0   1   1  10   5]
 [  0   0  13   1 156   2   0   1   4   9]
 [  0   0   4   1  88   0   0   0   0  79]]
Epoch 3/20, Loss: -0.1521


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3607
Validation Recall:     0.3607
Validation Precision:  0.2990
Validation F1 Score:   0.2557
Macro-Averaged F1:     0.1114
Micro-Averaged F1:     0.3607

Confusion Matrix:
[[   0    0    7    1  179    0    0    2    5   10]
 [   0    0    7    3   66    0    0    0    3   16]
 [   0    1  115    1  725    3    0    5    4   28]
 [   0    0    9    0  103    0    0    0    0   16]
 [   0    0   67    2 1032    2    1   15   16   70]
 [   0    0   12    0  227    4    0    0    2    2]
 [   0    0   13    0   68    0    0    0    0    7]
 [   0    0   13    1  162    0    0    1    0    1]
 [   0    0   10    0  171    0    0    0    2    3]
 [   0    0    6    0   99    0    0    0    0   67]]
Epoch 4/20, Loss: -0.2059


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3749
Validation Recall:     0.3749
Validation Precision:  0.3119
Validation F1 Score:   0.2623
Macro-Averaged F1:     0.1162
Micro-Averaged F1:     0.3749

Confusion Matrix:
[[   0    0    5    1  189    0    0    2    0    7]
 [   0    0    7    1   76    0    0    0    1   10]
 [   0    1  118    1  736    2    0    4    1   19]
 [   0    0   10    0  110    0    0    0    0    8]
 [   0    0   66    1 1083    0    0   16    4   35]
 [   0    0   11    0  231    2    0    0    2    1]
 [   0    0   13    0   73    0    0    0    0    2]
 [   0    0    9    0  168    0    0    1    0    0]
 [   0    0   12    0  173    0    0    0    0    1]
 [   0    0    6    0  101    0    0    0    0   65]]
Epoch 5/20, Loss: -0.2596


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3808
Validation Recall:     0.3808
Validation Precision:  0.3546
Validation F1 Score:   0.2681
Macro-Averaged F1:     0.1199
Micro-Averaged F1:     0.3808

Confusion Matrix:
[[   0    0    4    0  193    0    0    2    0    5]
 [   0    0    5    1   81    0    0    0    0    8]
 [   0    1  127    0  737    1    0    4    0   12]
 [   0    0   10    1  114    0    0    0    0    3]
 [   0    0   64    0 1099    0    0   17    0   25]
 [   0    0   12    0  230    2    0    1    1    1]
 [   0    0   13    0   73    0    0    0    0    2]
 [   0    0    7    0  170    0    0    1    0    0]
 [   0    0   12    0  173    0    0    0    0    1]
 [   0    0    5    0  108    0    0    0    0   59]]
Epoch 6/20, Loss: -0.3134


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3835
Validation Recall:     0.3835
Validation Precision:  0.3690
Validation F1 Score:   0.2709
Macro-Averaged F1:     0.1202
Micro-Averaged F1:     0.3835

Confusion Matrix:
[[   0    0    4    0  193    0    0    2    0    5]
 [   0    0    5    1   82    0    0    0    0    7]
 [   0    1  133    0  737    0    0    4    0    7]
 [   0    0   12    0  114    0    0    0    0    2]
 [   0    0   62    0 1106    0    0   17    0   20]
 [   0    0   12    0  232    1    0    1    1    0]
 [   0    0   14    0   72    0    0    0    0    2]
 [   0    0    7    0  168    0    0    3    0    0]
 [   0    0   12    0  173    0    0    0    0    1]
 [   0    0    5    0  112    0    0    0    0   55]]
Epoch 7/20, Loss: -0.3668


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3852
Validation Recall:     0.3852
Validation Precision:  0.3696
Validation F1 Score:   0.2732
Macro-Averaged F1:     0.1228
Micro-Averaged F1:     0.3852

Confusion Matrix:
[[   0    0    4    0  194    0    0    2    0    4]
 [   0    0    5    1   82    0    0    0    0    7]
 [   0    1  136    0  734    0    0    4    0    7]
 [   0    0   13    0  113    0    0    0    0    2]
 [   0    0   67    0 1107    0    0   16    0   15]
 [   0    0   12    0  232    1    0    1    1    0]
 [   0    0   18    0   68    0    0    0    0    2]
 [   0    0    5    0  170    0    0    3    0    0]
 [   0    0   13    0  172    0    0    0    0    1]
 [   0    0    4    0  111    0    0    0    0   57]]
Epoch 8/20, Loss: -0.4207


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3888
Validation Recall:     0.3888
Validation Precision:  0.3785
Validation F1 Score:   0.2775
Macro-Averaged F1:     0.1236
Micro-Averaged F1:     0.3888

Confusion Matrix:
[[   0    0    4    0  194    0    0    2    0    4]
 [   0    0    6    1   81    0    0    0    0    7]
 [   0    1  144    0  727    0    0    4    0    6]
 [   0    0   14    0  113    0    0    0    0    1]
 [   0    0   60    0 1114    0    0   17    0   14]
 [   0    0   11    0  233    2    0    1    0    0]
 [   0    0   19    0   67    0    0    0    0    2]
 [   0    0    3    0  171    0    0    4    0    0]
 [   0    0   12    0  173    0    0    0    0    1]
 [   0    0    5    0  115    0    0    0    0   52]]
Epoch 9/20, Loss: -0.4746


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3888
Validation Recall:     0.3888
Validation Precision:  0.3546
Validation F1 Score:   0.2783
Macro-Averaged F1:     0.1228
Micro-Averaged F1:     0.3888

Confusion Matrix:
[[   0    0    3    0  196    0    0    2    0    3]
 [   0    0    5    1   82    0    0    0    0    7]
 [   0    0  149    0  723    0    0    4    0    6]
 [   0    0   14    0  113    0    0    0    0    1]
 [   1    0   63    0 1112    0    0   17    0   12]
 [   0    0   12    0  233    2    0    0    0    0]
 [   0    0   19    0   67    0    0    0    0    2]
 [   0    0    2    0  172    0    0    4    0    0]
 [   0    0   13    0  171    1    0    0    0    1]
 [   0    0    8    0  115    0    0    0    0   49]]
Epoch 10/20, Loss: -0.5279


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3911
Validation Recall:     0.3911
Validation Precision:  0.3591
Validation F1 Score:   0.2826
Macro-Averaged F1:     0.1244
Micro-Averaged F1:     0.3911

Confusion Matrix:
[[   0    0    4    0  195    0    0    2    0    3]
 [   0    0    4    1   84    0    0    0    0    6]
 [   0    0  161    0  710    0    0    5    0    6]
 [   0    0   14    0  113    0    0    0    0    1]
 [   1    0   68    0 1109    0    0   17    0   10]
 [   0    0   12    0  233    2    0    0    0    0]
 [   0    0   19    0   67    0    0    0    0    2]
 [   0    0    1    0  173    0    0    4    0    0]
 [   0    0   13    0  172    1    0    0    0    0]
 [   0    0    8    0  116    0    0    0    0   48]]
Epoch 11/20, Loss: -0.5816


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.3970
Validation Recall:     0.3970
Validation Precision:  0.3972
Validation F1 Score:   0.2914
Macro-Averaged F1:     0.1289
Micro-Averaged F1:     0.3970

Confusion Matrix:
[[   1    0    4    0  193    0    0    3    0    3]
 [   0    0    4    1   84    0    0    0    0    6]
 [   0    0  180    0  691    0    0    5    0    6]
 [   0    0   14    0  113    0    0    0    0    1]
 [   1    0   70    0 1109    0    0   17    0    8]
 [   0    0   13    0  232    2    0    0    0    0]
 [   0    0   21    0   65    0    0    0    0    2]
 [   0    0    1    0  172    0    0    5    0    0]
 [   0    0   13    0  172    1    0    0    0    0]
 [   0    0    8    0  117    0    0    0    0   47]]
Epoch 12/20, Loss: -0.6357


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4003
Validation Recall:     0.4003
Validation Precision:  0.3993
Validation F1 Score:   0.2958
Macro-Averaged F1:     0.1297
Micro-Averaged F1:     0.4003

Confusion Matrix:
[[   1    0    4    0  193    0    0    3    0    3]
 [   0    0    4    1   84    0    0    0    0    6]
 [   0    0  192    0  678    0    0    6    0    6]
 [   0    0   15    0  112    0    0    0    0    1]
 [   1    0   69    0 1109    0    0   16    0   10]
 [   0    0   14    0  231    2    0    0    0    0]
 [   0    0   22    0   64    0    0    0    0    2]
 [   0    0    1    0  172    0    0    5    0    0]
 [   0    0   14    0  171    1    0    0    0    0]
 [   0    0    9    0  117    0    0    0    0   46]]
Epoch 13/20, Loss: -0.6892


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4015
Validation Recall:     0.4015
Validation Precision:  0.4003
Validation F1 Score:   0.2983
Macro-Averaged F1:     0.1309
Micro-Averaged F1:     0.4015

Confusion Matrix:
[[   1    0    4    0  193    0    0    3    0    3]
 [   0    0    4    1   85    0    0    0    0    5]
 [   0    0  200    0  670    0    0    6    0    6]
 [   0    0   16    0  111    0    0    0    0    1]
 [   1    0   74    0 1105    0    0   16    0    9]
 [   0    0   13    0  232    2    0    0    0    0]
 [   0    0   23    0   63    0    0    0    0    2]
 [   0    0    1    0  172    0    0    5    0    0]
 [   0    0   14    0  171    1    0    0    0    0]
 [   0    0    9    0  117    0    0    0    0   46]]
Epoch 14/20, Loss: -0.7425


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4032
Validation Recall:     0.4032
Validation Precision:  0.4023
Validation F1 Score:   0.3013
Macro-Averaged F1:     0.1327
Micro-Averaged F1:     0.4032

Confusion Matrix:
[[   1    0    4    0  193    0    0    3    0    3]
 [   0    0    4    1   84    0    0    1    0    5]
 [   0    0  207    0  662    0    0    7    0    6]
 [   0    0   17    0  110    0    0    0    0    1]
 [   1    0   75    0 1103    0    0   17    0    9]
 [   0    0   13    0  232    2    0    0    0    0]
 [   0    0   24    0   62    0    0    0    0    2]
 [   0    0    1    0  171    0    0    6    0    0]
 [   0    0   13    0  172    1    0    0    0    0]
 [   0    0   10    0  116    0    0    0    0   46]]
Epoch 15/20, Loss: -0.7970


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4047
Validation Recall:     0.4047
Validation Precision:  0.4037
Validation F1 Score:   0.3035
Macro-Averaged F1:     0.1330
Micro-Averaged F1:     0.4047

Confusion Matrix:
[[   1    0    4    0  193    0    0    3    0    3]
 [   0    0    4    1   84    0    0    1    0    5]
 [   0    0  214    0  655    0    0    7    0    6]
 [   0    0   17    0  110    0    0    0    0    1]
 [   1    0   75    0 1102    0    0   18    0    9]
 [   0    0   13    0  232    2    0    0    0    0]
 [   0    0   24    0   62    0    0    0    0    2]
 [   0    0    1    0  171    0    0    6    0    0]
 [   0    0   14    0  171    1    0    0    0    0]
 [   0    0   10    0  117    0    0    0    0   45]]
Epoch 16/20, Loss: -0.8501


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4062
Validation Recall:     0.4062
Validation Precision:  0.3929
Validation F1 Score:   0.3056
Macro-Averaged F1:     0.1334
Micro-Averaged F1:     0.4062

Confusion Matrix:
[[   1    0    4    0  193    0    0    3    0    3]
 [   0    0    4    1   84    0    0    1    0    5]
 [   0    0  221    0  649    0    0    6    0    6]
 [   0    0   17    0  110    0    0    0    0    1]
 [   1    0   75    0 1101    1    0   19    0    8]
 [   0    0   13    0  232    2    0    0    0    0]
 [   0    0   25    0   61    0    0    0    0    2]
 [   0    0    2    0  170    0    0    6    0    0]
 [   0    0   15    0  170    1    0    0    0    0]
 [   0    0   10    0  118    0    0    0    0   44]]
Epoch 17/20, Loss: -0.9042


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4092
Validation Recall:     0.4092
Validation Precision:  0.4059
Validation F1 Score:   0.3100
Macro-Averaged F1:     0.1370
Micro-Averaged F1:     0.4092

Confusion Matrix:
[[   2    0    4    0  193    0    0    2    0    3]
 [   0    0    4    1   83    1    0    1    0    5]
 [   0    0  228    0  642    0    0    6    0    6]
 [   0    0   18    0  109    0    0    0    0    1]
 [   1    0   75    0 1101    1    0   19    0    8]
 [   0    0   15    0  229    3    0    0    0    0]
 [   0    0   26    0   60    0    0    0    0    2]
 [   0    0    1    0  170    0    0    7    0    0]
 [   0    0   15    0  170    1    0    0    0    0]
 [   0    0   10    0  118    0    0    0    0   44]]
Epoch 18/20, Loss: -0.9576


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4103
Validation Recall:     0.4103
Validation Precision:  0.4067
Validation F1 Score:   0.3116
Macro-Averaged F1:     0.1371
Micro-Averaged F1:     0.4103

Confusion Matrix:
[[   2    0    4    0  193    0    0    2    0    3]
 [   0    0    4    1   83    1    0    1    0    5]
 [   0    0  234    0  636    0    0    6    0    6]
 [   0    0   18    0  109    0    0    0    0    1]
 [   1    0   77    0 1100    1    0   18    0    8]
 [   0    0   15    0  229    3    0    0    0    0]
 [   0    0   27    0   59    0    0    0    0    2]
 [   0    0    1    0  170    0    0    7    0    0]
 [   0    0   15    0  170    1    0    0    0    0]
 [   0    0   10    0  119    0    0    0    0   43]]
Epoch 19/20, Loss: -1.0111


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
<ipython-input-17-d860726ae668>:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels).to(device)


Validation Accuracy:  0.4103
Validation Recall:     0.4103
Validation Precision:  0.4066
Validation F1 Score:   0.3118
Macro-Averaged F1:     0.1369
Micro-Averaged F1:     0.4103

Confusion Matrix:
[[   2    0    5    0  192    0    0    2    0    3]
 [   0    0    4    1   83    1    0    1    0    5]
 [   0    0  236    0  635    0    0    6    0    5]
 [   0    0   18    0  109    0    0    0    0    1]
 [   1    0   78    0 1099    1    0   18    0    8]
 [   0    0   15    0  229    3    0    0    0    0]
 [   0    0   27    0   59    0    0    0    0    2]
 [   0    0    1    0  169    0    0    8    0    0]
 [   0    0   15    0  170    1    0    0    0    0]
 [   0    0   13    0  118    0    0    0    0   41]]
Epoch 20/20, Loss: -1.0644


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Validation Accuracy:  0.4112
Validation Recall:     0.4112
Validation Precision:  0.4066
Validation F1 Score:   0.3132
Macro-Averaged F1:     0.1376
Micro-Averaged F1:     0.4112

Confusion Matrix:
[[   2    0    6    0  191    0    0    2    0    3]
 [   0    0    4    1   83    1    0    1    0    5]
 [   0    0  241    0  631    0    0    6    0    4]
 [   0    0   18    0  109    0    0    0    0    1]
 [   1    0   80    0 1097    1    0   18    0    8]
 [   0    0   16    0  228    3    0    0    0    0]
 [   0    0   27    0   59    0    0    0    0    2]
 [   0    0    1    0  169    0    0    8    0    0]
 [   0    0   16    0  169    1    0    0    0    0]
 [   0    0   14    0  117    0    0    0    0   41]]
